// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpbazhtqsdgffdgbslug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwYmF6aHRxc2RnZmZkZ2JzbHVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjM3MzgsImV4cCI6MjA2MzU5OTczOH0.dXApJu19pmwi1KnLnlXESoRwXGjs_bZQ3MNIPWnXWig";

// Decodificar o JWT para verificar o role
try {
  const [header, payload, signature] = SUPABASE_PUBLISHABLE_KEY.split('.');
  const decodedPayload = JSON.parse(atob(payload));
} catch (e) {
  console.error('Erro ao decodificar JWT:', e);
}

// Verificação da chave antes de criar o cliente
try {
  const [header, payload, signature] = SUPABASE_PUBLISHABLE_KEY.split('.');
  const decodedPayload = JSON.parse(atob(payload));
} catch (e) {}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

